// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsXpHPNnl4Ikel6wf7Hp9P5uDc6hC-VRs',
    appId: '1:1045872600901:web:e14c8337b234c149a7402c',
    messagingSenderId: '1045872600901',
    projectId: 'employee-scan',
    authDomain: 'employee-scan.firebaseapp.com',
    storageBucket: 'employee-scan.appspot.com',
    measurementId: 'G-0WF9Y17WL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi2A3Zp_HR2RVAixd7IH1761nbqHc7Wug',
    appId: '1:1045872600901:android:cce8684eaa902c36a7402c',
    messagingSenderId: '1045872600901',
    projectId: 'employee-scan',
    storageBucket: 'employee-scan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcE76JevjFdXBKWb2-ZojlqqkduOAKj4w',
    appId: '1:1045872600901:ios:8624aef435e6df48a7402c',
    messagingSenderId: '1045872600901',
    projectId: 'employee-scan',
    storageBucket: 'employee-scan.appspot.com',
    iosClientId: '1045872600901-4m63eeqd4kg8sahq79lq3g9ujf26oa4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeScan',
  );
}
